app:
  name: "Life"
  window:
    width: 600
    height: 600
  cell:
    size: 15
    rgb_color:
      active:
        - 0.3
        - 0.3
        - 0.3
      inactive:
        - 0.7
        - 0.7
        - 0.7

